cache:
  enable: true
minify: true
scheme: Gemini
darkmode: true
creative_commons:
  license: by-nc-sa
  size: small
  sidebar: true
  post: true
menu:
  首页: / || fa fa-home
  存档: /archives/ || fa fa-archive
  友链: /links/ || fa fa-link
  GitHub: https://github.com/ricky8955555/blog || fa-brands fa-github
  关于我: https://rkmiao.eu.org || fa fa-user
custom_logo: /images/profile.webp
open_graph:
  enable: true
  options:
    image: /images/profile.webp
