avatar: /images/profile.webp
author: Phrinky
signature: '可燃性物質です。'
social:
  email: rkmiao@duck.com
  github: //github.com/ricky8955555
  wechat:
  telegram: //t.me/ricky8955555
  twitter: //x.com/ricky8955555
  bilibili: //space.bilibili.com/17047320
profile_links:
  - name: ABOUT
    url: //rkmiao.eu.org
    icon: fa fa-user
about:
  enable: false
friends:
  HuajiTech: //huajitech.net
  酷丁的主页: //coldin.top
  深海小涛: //xtaolink.cn
  资源管理器博客: //www.zyglq.cn
  卡平南路: //kkkrza.link
  MBRjun-Blog: //www.mbrjun.cn
  泠风寒声の小窝: //blog.lfhsheng.com
  douziの小站: //douzii.cf
  小熊的博客: //bearcurb.blog
  Shucheng Li: //snli.org
  Restent's Notebook: //blog.gxres.net
  XieXiLin 的小站: //www.xiexilin.com
  晓雨杂记: //lihaoyu.cn
  unknown's Blog: //unk.org.cn
  LeZi 的猫窝: //leziblog.com
SEO_title: Phrinky's Blog
main_title: Phrinky's Blog
subtitle: Ricky 的各种日常捏
read_more_button: true
toc: true
reading_info: false
site_header_image: /images/105444644_p0.webp
post_header_image: /images/83990879_p0-cropped.webp
# post_header_image: 
copyright:
  enable: true
  license: '本文采用 <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 进行许可'
favicon: /images/favicon.ico
float_button_theme: rounded
show_categories: true
